services:
  - type: web
    name: cointracker
    env: node
    buildCommand: npm install
    startCommand: npm start
    plan: free
    branch: main
    region: oregon
    runtime: node
    rootDir: .
